### ISSUE TITLE
About the decoding of Tokenizer.

### ISSUE THREAD

**Issue by wutong4012** [Yuanhy1997/SeqDiffuSeq#11]
Hi, when I run the decode of the trained bpe tokenizer, I found the parameter 'skip_special_tokens' is not work. It means the final generate text including the '\</s\>, \<s\>, \<pad\>' etc.

Did you meet this problem? I know it can use the 'replace' function to solve it. But it is really resonable?

Thanks for you sharing your code !

**Comment by Yuanhy1997** [comment]
The problem is that when training the tokenizer, the special tokens are not added to the tokenizer as "special token", while they are added as normal tokens. That's why the skip arg not working. I'll add a fix to the TODO list. A simple work around is to filter the special tokens when before tokenizer's decoding, since the indices of the special tokens are 0,1,2. You don't need to use replace function afterwards.

**Comment by wutong4012** [comment]
Thank you for your feedback. I will close this issue.
